apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: forum-api
spec:
  selector:
    app: postgres
  ports:
   - port: 5432
     protocol: TCP
     targetPort: 5432
     name: postgres
  type: ClusterIP
